name: flutter_bta_functions
description: Some useful functions for Flutter
version: 1.0.0
homepage: https://github.com/Staheos/flutter_bta_functions

environment:
  sdk: '>=3.1.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: any
